package com.inetbanking.Testcases;

import java.io.IOException;

import javax.swing.text.PasswordView;

import org.apache.commons.lang3.RandomStringUtils;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.testng.Assert;
import org.testng.Reporter;
import org.testng.annotations.Test;

import com.inetbanking.PageObjects.AddCustomerPage;
import com.inetbanking.PageObjects.LoginPage;

import net.bytebuddy.utility.RandomString;

public class TC_AddCustomerTest003 extends BaseClass
{
	@Test
	public void addnewCustomer() throws InterruptedException, IOException
	{
		LoginPage lp = new LoginPage(driver);
		lp.SetUserName(username);
		Reporter.log("UserName Provided");
		lp.SetPassword(password);
		Reporter.log("Password Provided");
		lp.ClickSubmit();
		
		Thread.sleep(2000);
		
		AddCustomerPage addcust = new AddCustomerPage(driver);
		addcust.clickAddnewcustomer();
		Reporter.log("Providing Customer details...");
		addcust.customerName("Singh");
		Thread.sleep(2000);
		addcust.customerGender("Male");
		Thread.sleep(4000);
		addcust.customerDOB("10","10","1991");
		Thread.sleep(4000);
		addcust.customerAddress("INDIA");
		Thread.sleep(2000);
		addcust.customerCity("BANGALORE");
		Thread.sleep(2000);
		addcust.customerstate("KARNATAKA");
		Thread.sleep(2000);
		addcust.customerpinno("560016");
		Thread.sleep(2000);
		addcust.customertelephoneno("7022091892");
		Thread.sleep(2000);
		String email = randomstring()+"@gmail.com";		// just added domain "Gmail" with the autogenerated String
		addcust.customeremailid(email);
		addcust.customerPassword("qwerty");
		addcust.customerSubmit();
		Thread.sleep(2000);
		
		Reporter.log("Validation stgarted...");
		// Just to validate the confirmation message after customer is added successfully
		boolean res = driver.getPageSource().contains("Customer Registered Successfully");
		
		if (res== true)
		{
			Reporter.log("Test Case passed...");
			Assert.assertTrue(true);
		}
		
		else
		{
			Reporter.log("Test Case failed...");
			capturescreen(driver, "addnewCustomer");
			Assert.assertTrue(false);
			
		}
	}
}